### ISSUE TITLE
test_transpose_forward() out of index

### ISSUE THREAD

**Issue by LukeLIN-web** [dlsyscourse/hw1#16]
<img width="828" alt="839DDE6C20F7F9DC70F1589A4923F71B" src="https://github.com/dlsyscourse/hw1/assets/60426396/ef4c5dff-a135-4c25-92a2-2b7833814000">
<img width="828" alt="839DDE6C20F7F9DC70F1589A4923F71B" src="https://github.com/dlsyscourse/hw1/assets/60426396/49ffeed9-7a22-41a3-aa7d-0176714e5b5a">

```python
def test_transpose_forward():
    np.testing.assert_allclose(ndl.transpose(ndl.Tensor([[[1.95]],
       [[2.7 ]],
       [[3.75]]]), axes=(1, 2)).numpy(), np.array([[[1.95]],
       [[2.7 ]],
       [[3.75]]]))
```
It should be 0  1 2 , 3d tensor, Why it is out of index?

**Comment by lantel-wm** [comment]
Same error here. Did you solve it?

**Comment by MatchalatteR** [comment]
Same problem. the correct axes length should be 3 instead of 2.

**Comment by harsh1241e** [comment]
Can anybody provide the for trnaspose part ?
