### ISSUE TITLE
Maybe there is a typo in autograd.py ? 

### ISSUE THREAD

**Issue by MARD1NO** [dlsyscourse/hw1#4]
In here: https://github.com/dlsyscourse/hw1/blob/master/python/needle/autograd.py#L133

```python
self.cached_data
```

It seems like this code is not necessary

**Comment by yks72p** [comment]
actually, Tianqi Chen said the same in the Lecture 5 ([timecode link](https://youtu.be/cNADlHfHQHg?t=2428)). so this line is not required
